library(gmqn)
library(minfi)
library(impute)
library(data.table)
library(dplyr)

# rgSet = readRDS(file = "C:/Users/jack/PycharmProjects/TruDiagnostic/AltumAge/Pre_norm_RGset.Rds")
# Mset = preprocessRaw(rgSet)
# bmiq_betas = bmiq_parallel(m = data.frame(getMeth(Mset)), um = data.frame(getUnmeth(Mset)),type = '850k',ncpu = 10)
gc(reset = TRUE)
bmiq_betas = fread(file='C:/Users/jack/PycharmProjects/TruDiagnostic/Covariate models/blood type/data/BetaMatrix_Funnorm_RCP_normalized_betas_1642081709.csv', data.table=TRUE)
bmiq_betas = bmiq_betas %>% mutate_if(is.numeric, round, digits=6)
print(bmiq_betas, 'working')
bmiq_betas_imp = data.frame(impute.knn(as.matrix(bmiq_betas))$data)
print(bmiq_betas_imp, 'working')
colnames(bmiq_betas_imp) = sub("X","",colnames(bmiq_betas_imp))
write.csv(bmiq_betas_imp, "C:/Users/jack/PycharmProjects/TruDiagnostic/Covariate models/blood type/data/BetaMatrix_Funnorm_RCP_normalized_betas_1642081709 Imputed.csv")
gc(reset = TRUE)
